.website/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('', 
  
  (r'^pages/(?P<page>\w+)/$', 'djangoproject.website.views.page'),
  (r'^contact_us' ,  'djangoproject.website.views.contact_us'),    
  (r'^' ,  'djangoproject.website.views.index'),

  #(r'^login', 'login'),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to
from djangoproject.apomembers.urls import urlpatterns as apomemberspatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^djangoproject/', include('djangoproject.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'', include(apomemberspatterns)),
    # (r'^login$', 'djangoproject.apomembers.loginops.login'),
    (r'^logout$', 'djangoproject.apomembers.loginops.logout'),
    (r'^dologin$', 'djangoproject.apomembers.loginops.dologin'),
    (r'^(.*\.js)$', 'djangoproject.apomembers.static.js'),
    (r'^createaccount$', 'djangoproject.apomembers.loginops.createaccount'),
    (r'^docreateaccount$', 'djangoproject.apomembers.loginops.docreateaccount'),
    (r'^main$', 'djangoproject.apomembers.mainops.main'),
    (r'^resetpassword$', 'djangoproject.apomembers.mainops.resetPassword'),
    (r'^doresetpassword$', 'djangoproject.apomembers.mainops.doResetPassword'),
    (r'^unregister$', 'djangoproject.apomembers.mainops.unregister'),
    (r'^changeactive$', 'djangoproject.apomembers.mainops.changeActive'),
    (r'^enroll$', 'djangoproject.apomembers.mainops.enroll'),
    (r'^editprofile$', 'djangoproject.apomembers.mainops.editprofile'),
    (r'^doeditprofile$', 'djangoproject.apomembers.mainops.doeditprofile'),
    (r'^changepassword$', 'djangoproject.apomembers.mainops.changepassword'),
    (r'^contact$', 'djangoproject.apomembers.mainops.contact'),
    (r'^doContact$', 'djangoproject.apomembers.mainops.doContact'),
    (r'^service$', 'djangoproject.apomembers.serviceops.main'),
    (r'^service/escortsignup$', 'djangoproject.apomembers.serviceops.escort'),
    (r'^service/escort$', 'djangoproject.apomembers.serviceops.escortMain'),
    (r'^service/addescort$', 'djangoproject.apomembers.serviceops.addEscort'),
    (r'^service/deleteescort$', 'djangoproject.apomembers.serviceops.deleteEscort'),
    (r'^service/escortroster$', 'djangoproject.apomembers.serviceops.escortRoster'),
    (r'^addservice$', 'djangoproject.apomembers.serviceops.addService'),
    (r'^deleteservice$', 'djangoproject.apomembers.serviceops.deleteService'),
    (r'^reqs$', 'djangoproject.apomembers.reqsops.main'),
    (r'^reqs/committee$', 'djangoproject.apomembers.reqsops.committee'),
    (r'^reqs/docommittee$', 'djangoproject.apomembers.reqsops.doCommittee'),
    (r'^reqs/okdeniedcommittee$', 'djangoproject.apomembers.reqsops.okDeniedCommittee'),
    (r'^reqs/philanthropy$', 'djangoproject.apomembers.reqsops.philanthropy'),
    (r'^reqs/dophilanthropy$', 'djangoproject.apomembers.reqsops.doPhilanthropy'),
    (r'^reqs/okdeniedphilanthropy$', 'djangoproject.apomembers.reqsops.okDeniedPhilanthropy'),
    (r'^reqs/cancelpendingphilanthropy$', 'djangoproject.apomembers.reqsops.cancelPendingPhilanthropy'),
    (r'^reqs/meetings$', 'djangoproject.apomembers.reqsops.meetings'),
    (r'^reqs/doaddmeeting$', 'djangoproject.apomembers.reqsops.doAddMeeting'),
    (r'^reqs/doremovemeeting$', 'djangoproject.apomembers.reqsops.doRemoveMeeting'),
    (r'^admins$', 'djangoproject.apomembers.adminops.main'),
    (r'^admins/semesterstats$', 'djangoproject.apomembers.adminops.semesterStatistics'),
    (r'^admins/approvephilanthropy$', 'djangoproject.apomembers.adminops.approvePhil'),
    (r'^admins/addphilanthropy$', 'djangoproject.apomembers.adminops.addPhil'),
    (r'^admins/committee$', 'djangoproject.apomembers.adminops.committee'),
    (r'^admins/meetings$', 'djangoproject.apomembers.adminops.meetings'),
    (r'^admins/dues$', 'djangoproject.apomembers.adminops.dues'),
    (r'^admins/service$', 'djangoproject.apomembers.adminops.service'),
    (r'^admins/escort$', 'djangoproject.apomembers.adminops.escort'),
    (r'^admins/escorttraining$', 'djangoproject.apomembers.adminops.escortTraining'),
    (r'^admins/escortfix$', 'djangoproject.apomembers.adminops.escortFix'),
    (r'^admins/escortfixfinal$', 'djangoproject.apomembers.adminops.escortFixFinal'),
    (r'^admins/weekdayescort$', 'djangoproject.apomembers.adminops.weekdayEscort'),
    (r'^admins/specfams$', 'djangoproject.apomembers.adminops.specFams'),
    (r'^admins/execboard$', 'djangoproject.apomembers.adminops.execboard'),
    (r'^admins/pledgeclass$', 'djangoproject.apomembers.adminops.pledgeClass'),
    (r'^admins/probationsemesters$', 'djangoproject.apomembers.adminops.probationSemesters'),
    (r'^admins/probationusers$', 'djangoproject.apomembers.adminops.probationUsers'),
    (r'^admins/probation$', 'djangoproject.apomembers.adminops.probation'),
    (r'^admins/doprobation$', 'djangoproject.apomembers.adminops.doProbation'),
    (r'^admins/semester$', 'djangoproject.apomembers.adminops.semester'),
    (r'^admins/roster$', 'djangoproject.apomembers.adminops.roster'),
    (r'^admins/rostercontents/(.*)$', 'djangoproject.apomembers.adminops.rosterContents'),
    (r'^admins/info$', 'djangoproject.apomembers.adminops.info'),
    (r'^admins/card$', 'djangoproject.apomembers.adminops.card'),
    (r'^admins/familyroster$', 'djangoproject.apomembers.adminops.familyRoster'),
    (r'^admins/familyrostercontents/(.*)$', 'djangoproject.apomembers.adminops.familyRosterContents'),
    (r'^admins/doaddphilanthropy$', 'djangoproject.apomembers.adminops.doAddPhil'),
    (r'^admins/doremovephilanthropy$', 'djangoproject.apomembers.adminops.doRemovePhil'),
    (r'^admins/doapprovephilanthropy$', 'djangoproject.apomembers.adminops.doApprovePhil'),
    (r'^admins/dodenyphilanthropy$', 'djangoproject.apomembers.adminops.doDenyPhil'),
    (r'^admins/approvecommittee$', 'djangoproject.apomembers.adminops.doApproveCommittee'),
    (r'^admins/denycommittee$', 'djangoproject.apomembers.adminops.doDenyCommittee'),
    (r'^admins/doaddmeeting$', 'djangoproject.apomembers.adminops.doAddMeeting'),
    (r'^admins/doremovemeeting$', 'djangoproject.apomembers.adminops.doRemoveMeeting'),
    (r'^admins/setdues$', 'djangoproject.apomembers.adminops.setDues'),
    (r'^admins/addservice$', 'djangoproject.apomembers.adminops.addService'),
    (r'^admins/deleteservice$', 'djangoproject.apomembers.adminops.deleteService'),
    (r'^admins/addescort$', 'djangoproject.apomembers.adminops.addEscort'),
    (r'^admins/deleteescort$', 'djangoproject.apomembers.adminops.deleteEscort'),
    (r'^admins/changepermissions$', 'djangoproject.apomembers.adminops.changePermissions'),
    (r'^admins/changeexec$', 'djangoproject.apomembers.adminops.changeExec'),
    (r'^admins/addpledgeclass$', 'djangoproject.apomembers.adminops.addPledgeClass'),
    (r'^admins/endsemester$', 'djangoproject.apomembers.adminops.endSemester'),
    (r'^admins/setactivesemester$', 'djangoproject.apomembers.adminops.setActiveSemester'),
    (r'^admins/addsemester$', 'djangoproject.apomembers.adminops.addSemester'),
    (r'^admins/addtraining$', 'djangoproject.apomembers.adminops.addTraining'),
    (r'^admins/setfamilyhead$', 'djangoproject.apomembers.adminops.setFamilyHead'),
    (r'^admins/setweekdayescort$', 'djangoproject.apomembers.adminops.setWeekdayEscort'),
    (r'^admins/addtospecfam$', 'djangoproject.apomembers.adminops.addToSpecFam'),
    (r'^admins/removefromspecfam$', 'djangoproject.apomembers.adminops.removeFromSpecFam'),
    (r'^$', redirect_to, {'url': '/main'}),
    (r'^login.php$', redirect_to, {'url': '/main'}),
    (r'^main.php$', redirect_to, {'url': '/main'}),
)

.website/models.py
from django.db import models



class link_location(models.Model):
    link=models.CharField(maxlength=60)
    def __str__(self):
        return self.link
    class Admin:
        pass

class Page(models.Model):
    name=models.CharField(maxlength=20,core=True)
    description = models.TextField(null=True, blank=True)
    link_location=models.ManyToManyField(link_location,null=True, blank=True,filter_interface=True)
    def __str__(self):
        return self.name
    class Admin:
	list_display = ('name', )
        search_fields = ( 'name',)
        js = ('js/tiny_mce/tiny_mce.js'),('js/tiny_mce/textareas.js') ,
        #js = ('js/xinha/init.js'),('js/xinha/htmlarea.js'),('js/xinha/description.js'),

.website/views.py
from djangoproject.website.models import *

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import loader, RequestContext


CONFIG={}

def getnavigation():
    links=link_location.objects.select_related()
    return links

from django.views.generic import list_detail
def index(request):
    'start page'
    links=link_location.objects.select_related()
    return list_detail.object_list(request, links,
    allow_empty=True,
    template_name='index.html')
    
def page(request,page=''):
    'page content'
    links=link_location.objects.select_related()
    page_c=Page.objects.get(name=page)
    return list_detail.object_list(request, links,
    extra_context = {
                   'page':page_c,
                    },
    allow_empty=True,
    template_name='page.html')





from django import forms
from django.core import validators
class ContactManipulator(forms.Manipulator):
    def __init__(self):
        self.fields = (
            forms.EmailField(field_name="your email", is_required=True),
            forms.TextField(field_name="name", length=25, maxlength=200, is_required=True),
            forms.LargeTextField(field_name="message", is_required=True),
        )
        

def contact_us(request):
    from djangoproject.settings import ADMINS
    manipulator = ContactManipulator()
    email_to=ADMINS[0][1]
    if request.POST:
        new_data = request.POST.copy()
        errors = manipulator.get_validation_errors(new_data)
        if not errors:
            manipulator.do_html2python(new_data)

            # Send e-mail using new_data here...
            from django.core.mail import send_mail, BadHeaderError
            try:
                subject='djangoproject message from  %s' % new_data['name']
                from_email=new_data['your email']
                message=new_data['message']
                send_mail(subject, message, from_email,[email_to], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            nav=getnavigation()
            return list_detail.object_list(request, nav,template_name='contact_us_thanks.html')
    else:
        errors = new_data = {}
    nav=getnavigation()
    form = forms.FormWrapper(manipulator, new_data, errors)
    return list_detail.object_list(request, nav,template_name='contact_form.html',extra_context ={'form': form})

.website/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="description" content="#" />
<meta name="keywords" content="#" />
<meta name="author" content="#" />
<link rel="stylesheet" type="text/css" href="/static/prozac_afternoon.css" media="screen" />
<title>Django : hosting</title>
</head>
<body>
<div class="wrap clearfix">
{% autoescape off %}
  <div class="header"><strong>Welcome:</strong> Our new django powered website </div>
  <div class="topnav" id="nav">{% block topnav %}
    <ul>
      <li><a href="#">home</a></li>
      <li><a href="#">about</a></li>
      <li><a href="#">forum</a></li>
      <li><a href="#">design</a></li>
      <li><a href="#">info</a></li>
      <li><a href="#">contact</a></li>
    </ul>{% endblock %}
  </div>
  <div class="container clearfix">
    <div class="news_right clearfix" id="news">
      <div class="news_cnr_top"><img src="/static/images/cnr_tl.gif" alt="" width="8" height="8" class="cnr" style="display: none" /></div>{%block rightbox %}
      {% endblock %}
      <div class="news_cnr_bottom"><img src="/static/images/cnr_bl.gif" alt="" width="8" height="8" class="cnr" style="display: none" /></div>
    </div>{%block mainbox %}
    
	{% endblock %}
  </div>
  <div class="footer" id="footer"> {% block footer %} <a href="#">home</a>&nbsp;&nbsp;:&nbsp;&nbsp; <a href="#">about</a>&nbsp;&nbsp;:&nbsp;&nbsp; <a href="#">forum</a>&nbsp;&nbsp;:&nbsp;&nbsp; <a href="#">design</a>&nbsp;&nbsp;:&nbsp;&nbsp; <a href="#">info</a>&nbsp;&nbsp;:&nbsp;&nbsp; <a href="#">contact</a> {% endblock %}</div>
{% endautoescape %}

</div>
</body>
</html>

.website/templates/contact_form.html
{% extends "index.html" %}

{%block mainbox %}

{% if form.has_errors %}
    <h2>Please correct the following error{{ errors|pluralize }}:</h2>
  {% endif %}

<form method="POST" action="contact_us">
<table>
{% for i in form.fields %}
<p><tr>
	<td><label for="id_{{i.field_name}}">{{i.field_name|title|removetags:"'_'"}}:</label></td>
	<td>{{i}}
	{% if i.errors %}
	*** {{ i.errors|join:", " }}
	{% endif %}
	</td>
</p></tr>	
{% endfor %}</table>
<input type="submit" value="submit" />
<input type="reset" value="Reset" />
</form>



{% endblock %}

.website/templates/contact_us_thanks.html
{% extends "index.html" %}

{%block mainbox %}

<p class="page_title">Thank you</p>

<p>We will try to answer to your query as soon as we can. </p>


{% endblock %}

.website/templates/index.html
{% extends "base.html" %}

{% block topnav %}
<ul>
	<li><a href="/">Home</a></li>
          {% for p in object_list.0.page_set.all %}
        <li><a href="/pages/{{p}}">{{p|capfirst}}</a>  </li>
    {%endfor%}
    <li><a href="/contact_us">Contact</a></li>
</ul>
{% endblock %}


{%block mainbox %}
{% for p in object_list.2.page_set.all %}
<p class="page_title">{{ p.name|capfirst}}</p>

<p>{{ p.description }}</p>
{%endfor%}

{% endblock %}



{%block rightbox %}
	{% for p in object_list.3.page_set.all %}
<p><span class="news_title">{{p.name|capfirst}}</span><br /></p>
<p>{{ p.description }}</p>  {%endfor%}  

{% endblock %}


{% block footer %}

          {% for p in object_list.1.page_set.all %}
        <a href="/pages/{{p}}">{{p|capfirst}}</a> |
    {%endfor%}
    
    <a href="/">Home</a> | <a href="/contact_us">Contact</a>
    
{% endblock %}

.website/templates/page.html
{% extends "index.html" %}

{%block mainbox %}

<p class="page_title">{{ page.name|capfirst}}</p>

<p>{{ page.description }}</p>


{% endblock %}